spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.docker.compose.enabled=true

# Chiave segreta per firmare il JWT (minimo 256 bit in Base64)
jwt.secret=7A25432A462D4A614E645267556B5870327335763879214125442A472D4B6150
jwt.expiration=86400000
# 86400000ms = 24 ore
